name: CI/CD for Spring Boot

# Trigger the workflow on push to main branch or pull request
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Java environment (Java 17 is commonly used with Spring Boot)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # Cache Maven dependencies to speed up builds
    - name: Cache Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Build the project with Maven
    - name: Build with Maven
      run: mvn clean package

    # Run tests
    - name: Run Tests
      run: mvn test
